apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hello-world-cicd
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: hello-world-cicd
              servicePort: http