apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
namespace: default
images:
- name: hello-world-cicd
  newName: sadokf/hello-world-cicd
  newTag: 48a619e37c5c85debd6365e56d354ba4b71c48a5
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
namespace: default
images:
- name: hello-world-cicd
  newName: sadokf/hello-world-cicd
  newTag: 48a619e37c5c85debd6365e56d354ba4b71c48a5
