apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: hello-world-cicd
images:
- name: hello-world-cicd
  newName: sadokf/hello-world-cicd
  newTag: 6a9e9ef67e8dff07ed9b62ef0a51cb6c8e503aed
