apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yml
- service.yml
- ingress.yml
namespace: hello-world-cicd
images:
- name: hello-world-cicd
  newName: sadokf/hello-world-cicd
  newTag: 2c41e15eacd06d4ddd09f4739729decc622a9c7c
